<?php
/*
 * The webapp is considered the view implementation of the entire web application,
 * containing bootstrap files to define dependencies in the engine. While WF is
 * a full-stack framework, it is used like Zend Framework with a bootstrap to bind
 * the framework to the implementor, where the implementor defines how WF should
 * run and what modules WF should load.
 *
 * This file is automatically generated, and should NOT be changed in any way.
 * There is no reason to change the contents of this file as this is mostly path
 * definitions, which would not change on the server during upgrades.
 */

date_default_timezone_set( 'UTC' );

// Define the deployment profile
define( 'ERROR_LEVEL', E_ALL | E_STRICT ); // Set to 0 for 'production', set to E_ALL for 'development'


$a = 'this-is-a-string';
echo preg_replace( '/(^|-)(.)/e', "strtoupper('\\2')", $a );

exit;
// Define environment paths
$CORE = dirname( __FILE__ ) . '/';
$IMPL = dirname( __FILE__ ) . '../morphine/';
include $CORE . 'painless.php';

// Create the workfloo object and define a distribution
$app = Painless::execute( 'edgeyo', $IMPL );

require_once "system/common/loader.php";

$loader = new Loader;