<?php

namespace Painless\System\Common;

require_once dirname(__FILE__) . '/../../../../painless/system/common/config.php';

/**
 * Test class for ConfigException.
 * Generated by PHPUnit on 2011-03-09 at 17:09:08.
 */
class ConfigExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ConfigException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ConfigException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
