<?php

namespace Painless\System\Common;

require_once dirname(__FILE__) . '/../../../../painless/system/common/loader.php';

/**
 * Test class for LoaderException.
 * Generated by PHPUnit on 2011-03-09 at 17:11:18.
 */
class LoaderExceptionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var LoaderException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoaderException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
