<?php

namespace Painless\System\Common;

require_once dirname(__FILE__) . '/../../../../painless/system/common/loader.php';

/**
 * Test class for Loader.
 * Generated by PHPUnit on 2011-03-09 at 17:11:18.
 */
class LoaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Loader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = Painless::load( 'com://system/common/loader' );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testLoad().
     */
    public function testLoad() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}

?>
